### PR TITLE
Update the common interface bindings

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by PerezHz** [comment]
Thanks, Chris! Is this ready to be merged or do you want to add some more changes?

@lbenet : do you think it would be worth to tag a new TaylorIntegration version (v0.2.2; current is v0.2.1) after merging this, since changes included in DiffEqBase v3.8.0 are breaking?

**Comment by ChrisRackauckas** [comment]
It would require a minor (0.3.0) because of the minimum version bound change.

>Is this ready to be merged or do you want to add some more changes?

I don't think there's anything else to do here.

**Comment by PerezHz** [comment]
> It would require a minor (0.3.0) because of the minimum version bound change.

You're right; I agree

> I don't think there's anything else to do here.

Ok, great! I'll merge right away!

**Comment by PerezHz** [comment]
Again, many thanks, Chris!

**Pull request merged**
