### PR TITLE
Fix a test: increase  tolerance,  using it for all integration steps

### PR DESCRIPTION
**Pull request by lbenet**
The fix was motivated by a broken test in Julia 1.3 but not in Julia 1.2 (#79)

### CODE REVIEW

**Comment by lbenet** [comment]
The problem with the tests seems to be related to `DiffEqBase` which introduced in v6.0.0 some breaking changes with respect to v5.0.

**Comment by PerezHz** [comment]
After taking a look at the changes in DiffEqBase.jl, I realized it was mainly related to the handling of the `callback` argument in `solve`. I was able to fix tests locally (although I'm not 100% sure if it's the right approach); I can push that fix here to see if it helps...

**Comment by PerezHz** [comment]
Just pushed an attempt to fix the issues with DiffEqBase to see how travis and appveyor react

**Comment by lbenet** [comment]
Thanks @PerezHz for pushing the changes. I just pushed another commit to include tests in Julia v1.2 and 1.3.

**Comment by lbenet** [comment]
Once travis finishes, I think we should merge and prepare a new tag. Since we are requiring DiffEqsBase >= 6, I guess a minor version would be appropriate. In that case, I would suggest to get rid of the `info` message displayed about the breaking changes that happened in v0.5. 

@PerezHz What do you think about this?

**Comment by PerezHz** [comment]
> What do you think about this?

I fully agree! I can take care of the new release in another PR after this one is merged

**Comment by lbenet** [comment]
Great! Thanks a lot!

**Comment by lbenet** [comment]
Thanks!

**Pull request merged**
