### PR TITLE
Add backward integration support in lyap_taylorinteg

### PR DESCRIPTION
**Pull request by PerezHz**

### CODE REVIEW

**Review by lbenet — APPROVED** [review]
LGTM!

**Comment by lbenet** [comment]
Thanks a lot for spotting the lack of  backward integration in `lyap_taylorinteg`. I'm in favor of merging this. Is this ready?

**Comment by lbenet** [comment]
Maybe  we should tag a new patch version?

**Comment by PerezHz** [comment]
> Thanks a lot for spotting the lack of backward integration in lyap_taylorinteg. I'm in favor of merging this. Is this ready?

Thank you for taking a look into this; it is indeed ready for merging!

> Maybe we should tag a new patch version?

I agree; I'll update the version number here so that we can register and tag a new release immediately after merging

**Comment by lbenet** [comment]
I'll let travis do its job, and then merge it. Thanks a lot!

**Comment by lbenet** [comment]
Travis completed ok; so I'll go ahead and merge this. Thanks a lot!

**Pull request merged**
