### PR TITLE
Add support for time evaluation points as a Vector{T} where T<:Real

### PR DESCRIPTION
**Pull request by PerezHz**
This PR adds new functionality for `taylorinteg`. Currently, `taylorinteg` accepts the integration time either as initial `t0::T` and final `tmax::T` times, or as a `Range{T}`, where `T<:Real`. The second case allows us to get the integrated solution only at the points specified by time `Range` objects such as `tr = 0.0:0.1:1.0`. This PR adds the ability to specify the evaluation points as a `Vector{T}`, so that the evaluation points may be unevenly-spaced; that is, we will be able to do things such as:

```julia
tv = [-100.0, 0.2354, 0.7, 1.0]
xv = taylorinteg(f!, x0, tv, order, abstol)
```

for a given ODE defined by `f!`. Added corresponding tests and also updated some docstrings.

### CODE REVIEW

**Comment by PerezHz** [comment]
As a bonus, and this is work in progress, I'm updating a notebook in the examples section, with an interesting joint application of TaylorSeries.jl and TaylorIntegration.jl for high-order polynomial approximations to special functions and integral transforms (e.g., Fourier).

**Comment by PerezHz** [comment]
Just finished updating the example I mentioned above; travis and appveyor are now working and shouldn't have any troubles giving green lights 😄

**Comment by lbenet** [comment]
LGTM. Thanks! I'll wait to get green lights and then merge.

**Comment by lbenet** [comment]
Done!

**Pull request merged**
