### PR TITLE
WIP Taylor integration including the variational equations

### PR DESCRIPTION
**Pull request by lbenet**
This is work in progress, though it is ready for reviewing. It allows to integrate the trajectory together with the first variations, which are used to obtain the Lipunov spectrum. The neat thing is that everything is done *automatically*, the user only needs to provide the equations of motion, i.e., the linearized equations are computed with automatic differentiation `TaylorN`.
I will try to optimize this now, since (obviously) it is a bit slow.

In the process, I was able to avoid a superfluous integration using a small trick in `liap_taylorstep`, which I also included in the `taylorstep`, getting rid of some methods.

Tests are not passing, though this will be solved once we delete the validated integration checks.

### CODE REVIEW

**Comment by lbenet** [comment]
Incidentally, tests are still missing...

**Comment by lbenet** [comment]
Rebase to current master and push (-f) to get new check on the tests.

**Comment by lbenet** [comment]
Re-rebased to include last changes (jettransport.jl) in master

**Comment by PerezHz** [comment]
Merging, since this PR has no conflicts with latest master, and current tests are passing in travis/appveyor. Although testing coverage will diminish, this will be addressed in a future PR.

**Pull request merged**
