### PR TITLE
Fixes due to changes in TaylorSeries

### PR DESCRIPTION
**Pull request by lbenet**
This PR fixes few small issues, mostly related with jet transport, which are introduced by https://github.com/JuliaDiff/TaylorSeries.jl/pull/226 (see the discussion in https://github.com/JuliaDiff/TaylorSeries.jl/pull/225). In pass, I rearranged tests to reduce verbose.

### CODE REVIEW

**Comment by PerezHz** [comment]
Thanks for this contribution and for taking care here of the breaking changes in TaylorSeries! I would imagine that there is going to be a new tagged release after JuliaDiff/TaylorSeries.jl#226 is merged? So should we wait until that is solved?

**Comment by lbenet** [comment]
Rebased to current master...

**Comment by lbenet** [comment]
Tests are passing, though not all have finished (strange?). @PerezHz I think this is ready for review.

**Comment by PerezHz** [comment]
> Tests are passing, though not all have finished (strange?).

Lately I've observed the DiffEqs common interface tests to take a bit longer than usual, but haven't yet figured out what's causing this.

> I think this is ready for review.

Ok, I'll take a look right away!

**Comment by lbenet** [comment]
> Lately I've observed the DiffEqs common interface tests to take a bit longer than usual, but haven't yet figured out what's causing this.

Is it maybe related with the new dependency (`OrdinaryDiffEq.jl`)? Why do we actually require it?

**Comment by mforets** [comment]
> Is it maybe related with the new dependency (OrdinaryDiffEq.jl)? Why do we actually require it?

https://github.com/PerezHz/TaylorIntegration.jl/pull/78#issuecomment-530532453

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/9e0e530dd27fac347ee64b1a98d25ff50b04ec97/src/solve.jl#L411

if it's really just to pull one function, i think it would be preferable to copy it to `TaylorIntegration.jl` (but i haven't checked if this comment makes sense).

**Comment by lbenet** [comment]
I agree with @mforets

**Comment by PerezHz** [comment]
I just pushed a couple of commits which implement the changes suggested by @mforets; let's see how travis responds

**Comment by PerezHz** [comment]
I noticed the slow tests were also due to loading OrdinaryDiffEq in `test/common.jl`; I fixed them so that OrdinaryDiffEq is not required

**Comment by PerezHz** [comment]
Other than that, this PR LGTM, and I agree to merge this once we get the green lights from travis! Thanks @lbenet for the contribution and @mforets for the slow tests fix! Should we tag a patch version after this is merged?

**Comment by PerezHz** [comment]
Merging!

**Pull request merged**
