### PR TITLE
Test julia v1.10 (-rc1 for now)

### PR DESCRIPTION
**Pull request by PerezHz**

### CODE REVIEW

**Comment by PerezHz** [comment]
@lbenet sorry, hit the merge button before reading your comment! 😅 Opened this PR to address here any issues related to the newer julia versions

**Comment by lbenet** [comment]
Thanks for openning this draft, specially for including Julia 1.10 tests. Let's see how it behaves...

**Comment by PerezHz** [comment]
I'm seeing some tests reported as failed, but the actual failure does not happen in the test run step, rather on the coverage uploading step (see e.g. [here](https://github.com/PerezHz/TaylorIntegration.jl/actions/runs/6842402939/job/18603834765#step:9:11))

**Comment by PerezHz** [comment]
Found a way to get rid of the problems with coveralls, now the only remaining failing tests are on nightly...

**Comment by lbenet** [comment]
> Found a way to get rid of the problems with coveralls, now the only remaining failing tests are on nightly...

Great!

Just for the record, the tests that are not passing in nightly seem to be related to OrdinaryDiffEq failing to precompile: https://github.com/PerezHz/TaylorIntegration.jl/actions/runs/6843320933/job/18605787188?pr=174#step:6:423

If you think we should merge it now as it is, please go ahead, and in a different PR we solve the problem with OrdinaryDiffEq.

**Comment by PerezHz** [comment]
Thanks for spotting that! I agree to merge this as-is and then tackle the remaining failing tests on another PR!

**Comment by PerezHz** [comment]
> Just for the record, the tests that are not passing in nightly seem to be related to OrdinaryDiffEq failing to precompile: https://github.com/PerezHz/TaylorIntegration.jl/actions/runs/6843320933/job/18605787188?pr=174#step:6:423

@lbenet in the latest tests run, corresponding to the latest release (v0.14.4), the issues with OrdinaryDiffEq have disappeared and tests are now passing in nightly (see [these logs](https://github.com/PerezHz/TaylorIntegration.jl/actions/runs/6854316191))

**Comment by lbenet** [comment]
Excellent news! Do we need to update the Project.toml, or was this case already included in what we have?

**Comment by PerezHz** [comment]
> Excellent news! Do we need to update the Project.toml, or was this case already included in what we have?

It's already included, afaict so I think we don't need to update the Project.toml.

**Pull request merged**
