### PR TITLE
Update to Julia 0.7

### PR DESCRIPTION
**Pull request by lbenet**

### CODE REVIEW

**Comment by lbenet** [comment]
I had to comment some tests involving `Taylor1{Taylor1{T}}` in `test/rootfinding.jl`; the problem is related to some ambiguity in the promotion rules that has to be solved in `TaylorSeries..jl`. So I think this is essentially ready.

**Comment by lbenet** [comment]
Tests do not pass because the last version of TaylorSeries (compatible with Julia0.7) needs to be tagged.

**Comment by PerezHz** [comment]
Many thanks for this, @lbenet! Can confirm that locally tests pass with julia 0.7.0 and TaylorSeries current master... So we should wait for a new TaylorSeries tag before merging this, right?

**Comment by lbenet** [comment]
We may have to be a bit patient: `TaylorSeries.jl` is waiting for `IntervalArithmetics.jl` get a tagged version working on Julia 0.7; that version is ready (https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/194#issuecomment-414146699), but there seems to be some issues in METADATA (see https://github.com/JuliaLang/METADATA.jl/pull/17216).

cc @dpsanders

**Comment by lbenet** [comment]
Tests pass locally; they require v0.8.0 of TaylorSeries.jl

**Comment by lbenet** [comment]
Tests pass :-)

**Comment by PerezHz** [comment]
Since TaylorIntegration v0.3.1 has been tagged (see #54). I went ahead and rebased to current master. Tests pass locally, as well as in travis and appveyor. I propose that once JuliaLang/METADATA.jl#17778 is merged, we should tag v0.4.0, the first TaylorIntegration release fully compatible with julia 0.7/1.0. Many thanks for all the effort you put to bring TaylorIntegration to julia 0.7 and 1.0 @lbenet!

**Comment by PerezHz** [comment]
Update: JuliaLang/METADATA.jl#17778 has been merged

**Comment by lbenet** [comment]
Did you rebase to current master? Auch!!

**Comment by lbenet** [comment]
Tests pass. Merging.

**Pull request merged**
