### PR TITLE
Fix dense output

### PR DESCRIPTION
**Pull request by PerezHz**
This PR fixes a subtle bug in the dense output polynomials. This will require bumping a minor version, and perhaps adding a warning to users, since this change may break downstream code.

### CODE REVIEW

**Comment by PerezHz** [comment]
@lbenet tests are not currently passing on nightly, but otherwise this is now ready for review.

**Review by lbenet — APPROVED** [review]

**Comment by lbenet** [comment]
Thanks a lot! LGTM! While I agree to merge this, I suggest to wait a little bit to (have some time and) check some packages that depend on TaylorIntegration, and in case of necessity, also update them.

**Comment by lbenet** [comment]
Note that there seems to be [a test](https://github.com/PerezHz/TaylorIntegration.jl/actions/runs/5404746318/jobs/9819339149?pr=168#step:6:410) related to `@taylorize` which is not passing

**Comment by PerezHz** [comment]
> Note that there seems to be [a test](https://github.com/PerezHz/TaylorIntegration.jl/actions/runs/5404746318/jobs/9819339149?pr=168#step:6:410) related to @taylorize which is not passing

Indeed! I was thinking to maybe wait for nightlies to stabilize, or do you think it's worth to deal with it already?

**Comment by lbenet** [comment]
Let me have a look on it tomorrow...

**Comment by lbenet** [comment]
It seems that Julia nightly includes additional information related to the line that produced certain code, which is causing the problem.

**Comment by PerezHz** [comment]
I think I found the related change in julia: https://github.com/JuliaLang/julia/pull/44995

**Comment by PerezHz** [comment]
Thank you for the suggestion @lbenet! I think I found a workaround with `Base.remove_linenums!`, which in principle should work for all tested versions...

**Comment by PerezHz** [comment]
Got the green lights! I'll merge and trigger the new release!

**Pull request merged**
