### PR TITLE
Refine computation of the time size

### PR DESCRIPTION
**Pull request by lbenet**
Solves #66

### CODE REVIEW

**Comment by PerezHz** [comment]
Nice solution for #66! LGTM; is this ready for merging?

**Comment by lbenet** [comment]
Yes, I think so. Once this is merged, I'll rebase #70 against master

**Comment by mforets** [comment]
I tried the problem in [#66](https://github.com/PerezHz/TaylorIntegration.jl/issues/66#issue-432162307) with this branch and it works 👍

**Comment by lbenet** [comment]
@mforets Great! Thanks for the thumbs-up :-)

**Pull request merged**
