### PR TITLE
Fix indices of Taylor1 and TaylorN, which now start at 0

### PR DESCRIPTION
**Pull request by lbenet**
This is motivated by recent chanmges in TaylorSeries; see https://github.com/JuliaDiff/TaylorSeries.jl/pull/135

### CODE REVIEW

**Comment by lbenet** [comment]
Tests are failing because we haven't tagged a version in TaylorSeries, I presume...

**Comment by PerezHz** [comment]
Can confirm that tests are passing locally!

**Comment by PerezHz** [comment]
> Tests are failing because we haven't tagged a version in TaylorSeries, I presume...

Yes, as soon as there's a new tagged version of TaylorSeries, tests will pass!

**Comment by PerezHz** [comment]
We should update the REQUIRE file accordingly when new TaylorSeries version (I guess it'd be v0.7.0?) is released...

**Comment by lbenet** [comment]
I will add it soon; still this has to be considered once a new version is tagged in TaylorSeries...

**Comment by lbenet** [comment]
I just updated the REQUIRE file; let's see if tests pass now to merge...

**Comment by lbenet** [comment]
Mmmm....

**Comment by PerezHz** [comment]
Perhaps we should wait until the new TaylorSeries release is merged into METADATA.jl? I'd guess once it's merged there tests will pass here, since the travis log says it can't find TaylorSeries v0.7.0

**Comment by lbenet** [comment]
@PerezHz Restarted (once again) the tests in travis; I do not know how to do this in appveyor...

**Comment by PerezHz** [comment]
Great! Thanks for letting me know! Just restarted appveyor as well...

**Comment by PerezHz** [comment]
Windows and linux tests have already passed; only macOS is left... 👍

**Comment by PerezHz** [comment]
Merging!

**Comment by lbenet** [comment]
Thanks!

**Pull request merged**
