### PR TITLE
Statically add gifs

### LINKED ISSUE #59: Some gif's are not displayed in the docs
Opening this issue to remember that the gifs in the docs for [Poincaré maps](https://perezhz.github.io/TaylorIntegration.jl/latest/root_finding.html) are not displayed.

### PR DESCRIPTION
**Pull request by lbenet**
Another try to fix #59

### CODE REVIEW

**Comment by lbenet** [comment]
While everything seems to work ok, I get a `!! failed to run code block` in travis; see for instance [this line](https://travis-ci.org/PerezHz/TaylorIntegration.jl/jobs/454102645#L594).

**Comment by lbenet** [comment]
I am still getting the same error in travis as before; see [this](https://travis-ci.org/PerezHz/TaylorIntegration.jl/jobs/454205773#L594-L596). The generated html tries now to load the gif files located at `build/assets/figures` which is correct.

I am in favor of merging this, and see what happens. If this doesn't work, since the gif files are now statically in the repo, we can load those files.

@PerezHz Do you have any comments?

**Comment by lbenet** [comment]
Another good reason to merge this is that coveralls and codecov are running again

**Comment by lbenet** [comment]
@PerezHz Shall we merge this to see if it works?

**Comment by PerezHz** [comment]
> @PerezHz Shall we merge this to see if it works?

Many thanks @lbenet for this! This is looking good and can confirm that locally it works, and as far as I can see, things should work also in travis, so I'll go ahead and merge this to see what we get

**Pull request merged**
