### PR TITLE
Upper bound versions of dependencies

### PR DESCRIPTION
**Pull request by lbenet**
Related to [this comment](https://github.com/JuliaRegistries/General/pull/4612#issuecomment-545130953).

### CODE REVIEW

**Comment by PerezHz** [comment]
Thanks for this PR! LGTM; should we go ahead and merge? Since the only changed file is Project.toml, there shouldn't be any changes in coverage, so perhaps we should just dismiss the coveralls report here.

**Comment by lbenet** [comment]
Sorry @PerezHz for the long delay, and thanks for taking a look into this. 

I agree, we should not take in this case too seriously the failure in the coverage. Yet, maybe we should wait for #89 before merging this, and  tag a new patch version (trying to use the automatic merging machinery).

**Comment by PerezHz** [comment]
Rebased to current master

**Comment by lbenet** [comment]
#89 is merged. Do you think we can go ahead with this one? And perhaps also tag a new --perhaps patch, but it may not work the automatic merging-- version?

**Comment by PerezHz** [comment]
Just merged this PR, maybe I can try now to tag a new patch version?

**Comment by lbenet** [comment]
Thanks!

I do not think it will work as an automatic merge, but I don't think it should be a minor version

**Comment by PerezHz** [comment]
Just opened #90 in order to tag v0.7.1

**Comment by lbenet** [comment]
Thanks again!

**Pull request merged**
