### PR TITLE
Updates package versions

### PR DESCRIPTION
**Pull request by lbenet**
Remove carets from Project.toml and add newer versions

### CODE REVIEW

**Comment by PerezHz** [comment]
Thanks for this contribution, @lbenet! LGTM, especially after those fixes in `TaylorSeries.pow!` and `TaylorSeries.div!`! Is this ready to be merged?

**Comment by lbenet** [comment]
I just pushed another commit to bump a patch version. Yes, this is ready to e merged. Can you also register the new version?

**Comment by PerezHz** [comment]
> I just pushed another commit to bump a patch version.

Great, thanks!

> Yes, this is ready to e merged. Can you also register the new version?

Sure thing! Merging right away!

**Comment by lbenet** [comment]
Thanks a lot!

**Pull request merged**
