### PR TITLE
Backward integration

### LINKED ISSUE #37: Backwards integration
Right now, it's not possible to integrate ODEs backwards. I know it's that way by design, but why is it that way? 
Sometimes it's practical to integrate "to the past" and I think it would be a nice feature to have. 
I found this by trying to do a Newton's method around an specific time.

### PR DESCRIPTION
**Pull request by lbenet**
This PR introduces some flexibility in the way we handle the stepsize, which among others allows to perform some backward integrations.

Fixes #37

### CODE REVIEW

**Comment by lbenet** [comment]
cc @blas-ko

**Comment by lbenet** [comment]
@PerezHz I think this is ready for review

**Comment by lbenet** [comment]
@PerezHz Comments...? Suggestions...? Concerns...? Merging...?

**Comment by PerezHz** [comment]
@lbenet LGTM! It's nice to see #37 solved! Since tests are passing I'll merge this right away! Do you think this merits tagging a new patch i.e. v0.6.2?

**Comment by lbenet** [comment]
> Do you think this merits tagging a new patch i.e. v0.6.2?

I think it merits a new version, though I don't know if v0.6.2 is recommended, or v0.7.0.

**Comment by PerezHz** [comment]
Since new functionality was added but the changes are backwards-compatible, perhaps a minor version would be more appropriate?

**Comment by lbenet** [comment]
I agree. Thanks!

**Pull request merged**
