### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by mforets**
(this update is needed for upstream packages to build CI on Julia v1.6 like [here](https://travis-ci.org/github/JuliaReach/LazySets.jl/jobs/754446527#L499) -- or at least that's what i understand)

### CODE REVIEW

**Review by lbenet — APPROVED** [review]

**Comment by lbenet** [comment]
Do we need a new release (update patch version)?

**Comment by mforets** [comment]
yes , i think so

**Comment by mforets** [comment]
sorry to insist, could you please tag a new release?

**Comment by lbenet** [comment]
No problem, and sorry for the delay; it's (finally) on its way...

**Pull request merged**
