### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by lbenet**
This PR adds some basic documentation to the package. There are still lots of things missing, but this is a starting point. I think we should enlarge it a bit more, and once it is merged, we should tag a new version, which works on Julia 0.7 and 1.0.

I think we shouldn't take too much time on this.

### CODE REVIEW

**Comment by lbenet** [comment]
Rebased to current master...

**Comment by PerezHz** [comment]
Thank you a lot @lbenet for opening this PR! I went ahead and added docs for some of the features in the package (e.g., jet transport, Lyapunov spectrum, etc.); also, I added and updated some notebooks, and did some other scattered stuff... Please, let me know what you think! 😄 If there's anything that needs to be changed/added/etc., I'll be happy to do it

**Comment by lbenet** [comment]
Thanks a lot @PerezHz for commiting here. I'll take a look today or tomorrow and we can exchange some feedback.

**Comment by lbenet** [comment]
Relevant to this PR: https://discourse.julialang.org/t/psa-documenter-jl-breaking-changes-version-capping/16431

Though the last commit addresses this, we may opt to have a Project.toml file instead. @PerezHz Any comments?

**Comment by PerezHz** [comment]
> Though the last commit addresses this, we may opt to have a Project.toml file instead. @PerezHz Any comments?

Thanks for the ping! I just uploaded two commits:

- 6c1d8a9 is just some minor changes for consistency in how we write things in the Poincaré map example
- eb37798 addresses the changes that are occurring in Documenter following the info in the link you provided

**Comment by PerezHz** [comment]
I agree that we should add the docs/Project.toml, I went ahead and added it just to see how things work out, but feel free to change it if there's anything I missed

**Comment by PerezHz** [comment]
I'm gonna go ahead and merge to see how travis reacts, and then change things accordingly if necessary. Many thanks @lbenet for this PR!

**Comment by lbenet** [comment]
Thanks a lot to you too, not only for merging but for contributing to the docs as well!

**Pull request merged**
