### PR TITLE
Fix some cases where transpose could throw an error

### PR DESCRIPTION
**Pull request by lbenet**
A (non-elegant) solution to #27

### CODE REVIEW

**Comment by PerezHz** [comment]
Thanks, @lbenet! While there are still some tests running, so far the tests are all passing! Do you want me to check some performance benchmarks?

**Comment by lbenet** [comment]
@PerezHz There was a strange error in travis (nightly, in linux). Do you have any idea what is the problem?

**Comment by PerezHz** [comment]
> There was a strange error in travis (nightly, in linux). Do you have any idea what is the problem?

@lbenet  As far as the error log shows on both travis and appveyor, somewhere near julia-0.7-DEV.800, something has been broken; do you think we should wait for the error to be solved or should we file a bug report?

**Comment by PerezHz** [comment]
On my machine I'm testing with julia-0.7-DEV.798 and everything is working right!

**Comment by PerezHz** [comment]
Locally, tests are passing on julia 0.5.2, 0.6.0, and 0.7.0-DEV.810

**Comment by PerezHz** [comment]
Merging! Thanks, @lbenet!

**Pull request merged**
