### PR TITLE
Save gif-files in docs/build

### LINKED ISSUE #59: Some gif's are not displayed in the docs
Opening this issue to remember that the gifs in the docs for [Poincaré maps](https://perezhz.github.io/TaylorIntegration.jl/latest/root_finding.html) are not displayed.

### PR DESCRIPTION
**Pull request by lbenet**
This may fix #59. Locally it works, but I am not sure it does here.

### CODE REVIEW

**Comment by PerezHz** [comment]
Thanks for this PR!

We could try with this and see if it just works! Otherwise, from what I've seen in the Plots.jl docs (see e.g. [here](https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/src/index.md#simple-is-beautiful)), they don't actually let travis build the gif files; instead, they upload the gif files as part of a repo and then just post them where it corresponds, so I guess that would be another option just in case another option is needed.

**Comment by lbenet** [comment]
I'm in favor for testing what happens when merging. Locally, the file is (properly) saved in the `builds/` directory, which I think is the folder that gets uploaded. If this doesn't work, we can revert it. 

But we should think it over before doing anything.

**Comment by PerezHz** [comment]
Just merged to see what happens; as you said, if this doesn't work, then we may revert it

**Comment by lbenet** [comment]
It seems it didn't work...

**Comment by lbenet** [comment]
We should ask in discourse, or open an issue in Documenter.jl

**Pull request merged**
